name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  TKE_IMAGE_URL: ccr.ccs.tencentyun.com/sxu-oj/judger

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Build Docker image
      run: |        
        docker build -t ${TKE_IMAGE_URL}:${GITHUB_SHA} .

    - name: Login TCR Registry
      run: |
        docker login ccr.ccs.tencentyun.com --username=${{ secrets.REPO_USERNAME }} --passowrd='${{ secrets.REPO_PASSWORD  }}'

    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push ${TKE_IMAGE_URL}:${GITHUB_SHA}
